# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: "(B) 📅 Daily Build with auto-update"
on:
  workflow_dispatch:
    inputs:
      runtime_windows_artifact_workflow_run_id:
        description: "The workflow run ID for the Windows runtime artifact"
        required: false
        type: string
      runtime_linux_artifact_workflow_run_id:
        description: "The workflow run ID for the Linux runtime artifact"
        required: false
        type: string
      runtime_mac_artifact_workflow_run_id:
        description: "The workflow run ID for the macOS runtime artifact"
        required: false
        type: string
permissions:
  contents: write

jobs:
  package-windows:
    uses: ./.github/workflows/package.yml
    with:
      platform: Windows-x64
      runtime_artifact_workflow_run_id: ${{ inputs.runtime_windows_artifact_workflow_run_id }}
      beta: true
    secrets: inherit

  package-linux:
    uses: ./.github/workflows/package.yml
    with:
      platform: Linux-x64
      runtime_artifact_workflow_run_id: ${{ inputs.runtime_linux_artifact_workflow_run_id }}
      beta: true
    secrets: inherit

  package-macos:
    uses: ./.github/workflows/package.yml
    with:
      platform: macOS-x64
      runtime_artifact_workflow_run_id: ${{ inputs.runtime_mac_artifact_workflow_run_id }}
      beta: true
    secrets: inherit

  publishs:
    needs: [package-windows, package-linux, package-macos]
    uses: ./.github/workflows/publish_alpha.yml
    with:
      win_runtime_artifact_workflow_call: ${{ inputs.runtime_windows_artifact_workflow_run_id }}
      linux_runtime_artifact_workflow_call: ${{ inputs.runtime_linux_artifact_workflow_run_id }}
      mac_runtime_artifact_workflow_call: ${{ inputs.runtime_mac_artifact_workflow_run_id }}
