# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: "(A) 📦️ Package"

on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        options:
          - win-x64
          - linux-x64
      artifact_workflow_run_id:
        type: string
        required: true

run-name: 📦️ Package ${{inputs.platform == 'win-x64' && 'Windows x64' || 'Linux x64'}}
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: 'nyanrus/noraneko-runtime'
          submodules: "recursive"
      - name: Configure sccache
        uses: actions/github-script@v7
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: setup Rust 🦀
        run: |

          rustup default nightly
          rustup target add x86_64-pc-windows-msvc

          #? https://github.com/mozilla/sccache#known-caveats
          export CARGO_INCREMENTAL=0
      - uses: pnpm/action-setup@v4
        with:
          version: 9
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Setup Noraneko
        run: |

          cd $GITHUB_WORKSPACE

          # update noraneko to latest
          git submodule update --remote

          cd ./noraneko
          pnpm install
          cd ..
      - name: Setup 🪛
        run: |

          cp ./.github/workflows/mozconfigs/win64.mozconfig mozconfig
          # Copy Noraneko Branding
          cp -r ./noraneko/gecko/branding/* ./browser/branding/

          sudo apt install msitools -y

          #if [[ $GHA_debug == 'true' ]]; then
          #  echo "ac_add_options --enable-debug" >> mozconfig
          #fi

          ./mach --no-interactive bootstrap --application-choice browser
      - name: Write Versions
        run: |

          cd ./noraneko
          pnpm build --write-version
          cd ..
      - name: Mach configure
        run: |

          mkdir noraneko/gecko/config/autogenerated
          echo "$(cat browser/config/version.txt)@$(cat noraneko/gecko/config/version.txt)" >> noraneko/gecko/config/autogenerated/version.txt
          echo "$(cat browser/config/version_display.txt)@$(cat noraneko/gecko/config/version_display.txt)" >> noraneko/gecko/config/autogenerated/version_display.txt
          echo "ac_add_options --with-version-file-path=noraneko/gecko/config/autogenerated" >> mozconfig
          # sed -i 's|ac_add_options --disable-maintenance-service|#ac_add_options --disable-maintenance-service|g' ./mozconfig
          sed -i 's|ac_add_options --disable-updater|#ac_add_options --disable-updater|g' ./mozconfig
          sed -i 's|https://@MOZ_APPUPDATE_HOST@/update/6/%PRODUCT%/%VERSION%/%BUILD_ID%/%BUILD_TARGET%/%LOCALE%/%CHANNEL%/%OS_VERSION%/%SYSTEM_CAPABILITIES%/%DISTRIBUTION%/%DISTRIBUTION_VERSION%/update.xml|https://github.com/nyanrus/noraneko/releases/download/%VERSION%/%BUILD_TARGET%-%CHANNEL%-%OS_VERSION%-update.xml|g' ./build/application.ini.in
          echo "ac_add_options --enable-update-channel=alpha" >> mozconfig

          echo "ac_add_options --enable-artifact-builds" >> mozconfig
          ./mach configure
          git apply --ignore-space-change --ignore-whitespace .github/patches/packaging/*.patch
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{inputs.platform == 'win-x64' && 'noraneko-win-amd64-moz-artifact'}}
          run-id: ${{inputs.artifact_workflow_run_id}}
          github-token: ${{github.token}}
          repository: "nyanrus/noraneko-runtime"
          path: ~/

      - name: Build noraneko
        run: |

          cd ./noraneko
          NODE_ENV='production' pnpm build --release-build-before
          cd ..

      - name: build
        run: |
          MOZ_ARTIFACT_FILE=$(echo ~/noraneko-*.win64.zip) ./mach build
      - name: Inject noraneko
        run: |
          cd ./noraneko
          pnpm build --release-build-after
          cd ..
      - name: Package noraneko
        run: |
          ./mach package
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{'noraneko-dist-host'}}
          run-id: ${{inputs.artifact_workflow_run_id}}
          github-token: ${{github.token}}
          repository: "nyanrus/noraneko-runtime"
          path: obj-x86_64-pc-windows-msvc/dist/host

      - name: Create MAR package
        run: |
          chmod +x $(echo ./obj-*)/dist/host/bin/mar
          mkdir ~/noraneko-mar
          touch "$(echo ./obj-*)/dist/noraneko/precomplete"
          MAR="$(echo ./obj-*)/dist/host/bin/mar" MOZ_PRODUCT_VERSION=$(cat noraneko/gecko/config/version.txt) MAR_CHANNEL_ID=alpha ./tools/update-packaging/make_full_update.sh ~/noraneko-mar/noraneko-win-amd64-full.mar "$(echo ./obj-*)/dist/noraneko"
      - name: Publish Package 🎁
        uses: actions/upload-artifact@v4
        with:
          name: noraneko-win-amd64-moz-artifact
          path: obj-x86_64-pc-windows-msvc/dist/noraneko-*.zip
      - name: Publish Installer 🎁
        uses: actions/upload-artifact@v4
        with:
          name: noraneko-win-amd64-installer
          path: obj-x86_64-pc-windows-msvc/dist/install/sea/*
      - name: Publish MAR 🎁
        uses: actions/upload-artifact@v4
        with:
          name: noraneko-win-amd64-mar-full
          path: ~/noraneko-mar/*.mar
