# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.

name: "(A) |Œ±| Publish Alpha"

on:
  workflow_dispatch:
    inputs:
      platform:
        type: choice
        required: true
        default: Windows-x64
        options:
          - Windows-x64
          - Linux-x64
          - macOS-x64
      artifact_workflow_run_id:
        type: string
        required: false
        default: ""
  workflow_call:
    inputs:
      platform:
        type: string
        required: true
        default: Windows-x64
      artifact_workflow_run_id:
        type: string
        required: false
        default: ""

permissions:
  contents: write

run-name: "|Œ±| Publish Alpha"
jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Possibly retrieve run ID if not provided
        run: |
          if [ -z "${{ inputs.artifact_workflow_run_id }}" ]; then
            LATEST_ID=$(curl -s \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
              "https://api.github.com/repos/Floorp-Projects/Floorp-12/actions/workflows/package.yml/runs?branch=main&status=success" \
            | jq -r --arg platform "${{ inputs.platform }}" '
              [.workflow_runs[] | select(.display_title | endswith($platform))][0].id
            ')
            echo "ARTIFACT_WORKFLOW_RUN_ID=$LATEST_ID" >> $GITHUB_ENV
          else
            echo "ARTIFACT_WORKFLOW_RUN_ID=${{ inputs.artifact_workflow_run_id }}" >> $GITHUB_ENV
          fi

      - name: Set artifact name by platform
        run: |
          case "${{ inputs.platform }}" in
            "Windows-x64") ARTIFACT_NAME="noraneko-win-amd64-mar-full" ;;
            "Linux-x64")   ARTIFACT_NAME="noraneko-linux-amd64-mar-full" ;;
            "macOS-x64")   ARTIFACT_NAME="noraneko-mac-amd64-mar-full" ;;
          esac
          echo "ARTIFACT_NAME=$ARTIFACT_NAME" >> $GITHUB_ENV

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          run-id: ${{ env.ARTIFACT_WORKFLOW_RUN_ID }}
          github-token: ${{ github.token }}
          path: ~/noraneko-publish

      - name: Setup
        run: |
          pnpm i

          sudo apt install jq

          node --import @swc-node/register/esm-register ./scripts/update/xml.ts ~/noraneko-publish/meta.json ~/noraneko-publish/WINNT_x86_64-msvc-x64.update.xml

          echo "VERSION=$(cat ~/noraneko-publish/meta.json | jq '.version' | sed 's/"//g')" >> "$GITHUB_ENV"
          echo "NR_VERSION=$(cat ~/noraneko-publish/meta.json | jq '.noraneko_version' | sed 's/"//g')" >> "$GITHUB_ENV"
          echo "ROOT_DIR=$(echo ~)" >> "$GITHUB_ENV"

      - name: Deploy to GitHub Releases üöÄ
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{env.ROOT_DIR}}/noraneko-publish/WINNT_x86_64-msvc-x64.update.xml
            ${{env.ROOT_DIR}}/noraneko-publish/*.mar

          tag_name: "alpha"
          name: "Alpha Release"
          body: |
            "Noraneko Alpha: v${{ env.NR_VERSION }} (Firefox v${{ env.VERSION }})"
          draft: false
          prerelease: true
          token: ${{ github.token }}

      - name: Publish Package üéÅ
        uses: actions/upload-artifact@v4
        with:
          name: noraneko-publish
          path: ~/noraneko-publish/*
